// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"looklook/app/shop/cmd/rpc/internal/logic"
	"looklook/app/shop/cmd/rpc/internal/svc"
	"looklook/app/shop/cmd/rpc/pb"
)

type ShopServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedShopServer
}

func NewShopServer(svcCtx *svc.ServiceContext) *ShopServer {
	return &ShopServer{
		svcCtx: svcCtx,
	}
}

func (s *ShopServer) GetGoodsById(ctx context.Context, in *pb.GoodsReq) (*pb.GoodsResp, error) {
	l := logic.NewGetGoodsByIdLogic(ctx, s.svcCtx)
	return l.GetGoodsById(in)
}

func (s *ShopServer) GetGoodsList(ctx context.Context, in *pb.GoodsListReq) (*pb.GoodsListResp, error) {
	l := logic.NewGetGoodsListLogic(ctx, s.svcCtx)
	return l.GetGoodsList(in)
}
