// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"looklook/common/globalkey"
)

var (
	noticeSubscribeSettingFieldNames          = builder.RawFieldNames(&NoticeSubscribeSetting{})
	noticeSubscribeSettingRows                = strings.Join(noticeSubscribeSettingFieldNames, ",")
	noticeSubscribeSettingRowsExpectAutoSet   = strings.Join(stringx.Remove(noticeSubscribeSettingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noticeSubscribeSettingRowsWithPlaceHolder = strings.Join(stringx.Remove(noticeSubscribeSettingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNoticeNoticeSubscribeSettingIdPrefix                      = "cache:notice:noticeSubscribeSetting:id:"
	cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix = "cache:notice:noticeSubscribeSetting:userOpenid:msgTemplateId:"
)

type (
	noticeSubscribeSettingModel interface {
		Insert(ctx context.Context, data *NoticeSubscribeSetting) (sql.Result, error)
		TransInsert(ctx context.Context, session sqlx.Session, data *NoticeSubscribeSetting) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*NoticeSubscribeSetting, error)
		FindOneByUserOpenidMsgTemplateId(ctx context.Context, userOpenid string, msgTemplateId string) (*NoticeSubscribeSetting, error)
		Update(ctx context.Context, data *NoticeSubscribeSetting) error
		List(ctx context.Context, page, limit int64) ([]*NoticeSubscribeSetting, error)
		TransUpdate(ctx context.Context, session sqlx.Session, data *NoticeSubscribeSetting) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*NoticeSubscribeSetting, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*NoticeSubscribeSetting, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*NoticeSubscribeSetting, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*NoticeSubscribeSetting, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*NoticeSubscribeSetting, error)
		Delete(ctx context.Context, id int64) error
	}

	defaultNoticeSubscribeSettingModel struct {
		sqlc.CachedConn
		table string
	}

	NoticeSubscribeSetting struct {
		Id            int64         `db:"id"`
		UserOpenid    string        `db:"user_openid"`
		MsgTemplateId string        `db:"msg_template_id"`
		IsAccepted    sql.NullInt64 `db:"is_accepted"`
		CreateTime    time.Time     `db:"create_time"`
		UpdateTime    time.Time     `db:"update_time"`
	}
)

func newNoticeSubscribeSettingModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNoticeSubscribeSettingModel {
	return &defaultNoticeSubscribeSettingModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notice_subscribe_setting`",
	}
}

func (m *defaultNoticeSubscribeSettingModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	noticeNoticeSubscribeSettingIdKey := fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, id)
	noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey := fmt.Sprintf("%s%v:%v", cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix, data.UserOpenid, data.MsgTemplateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, noticeNoticeSubscribeSettingIdKey, noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey)
	return err
}

func (m *defaultNoticeSubscribeSettingModel) FindOne(ctx context.Context, id int64) (*NoticeSubscribeSetting, error) {
	noticeNoticeSubscribeSettingIdKey := fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, id)
	var resp NoticeSubscribeSetting
	err := m.QueryRowCtx(ctx, &resp, noticeNoticeSubscribeSettingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeSubscribeSettingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindOneByUserOpenidMsgTemplateId(ctx context.Context, userOpenid string, msgTemplateId string) (*NoticeSubscribeSetting, error) {
	noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey := fmt.Sprintf("%s%v:%v", cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix, userOpenid, msgTemplateId)
	var resp NoticeSubscribeSetting
	err := m.QueryRowIndexCtx(ctx, &resp, noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_openid` = ? and `msg_template_id` = ? limit 1", noticeSubscribeSettingRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userOpenid, msgTemplateId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) Insert(ctx context.Context, data *NoticeSubscribeSetting) (sql.Result, error) {
	noticeNoticeSubscribeSettingIdKey := fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, data.Id)
	noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey := fmt.Sprintf("%s%v:%v", cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix, data.UserOpenid, data.MsgTemplateId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, noticeSubscribeSettingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserOpenid, data.MsgTemplateId, data.IsAccepted)
	}, noticeNoticeSubscribeSettingIdKey, noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey)
	return ret, err
}

func (m *defaultNoticeSubscribeSettingModel) TransInsert(ctx context.Context, session sqlx.Session, data *NoticeSubscribeSetting) (sql.Result, error) {
	noticeNoticeSubscribeSettingIdKey := fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, data.Id)
	noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey := fmt.Sprintf("%s%v:%v", cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix, data.UserOpenid, data.MsgTemplateId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, noticeSubscribeSettingRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.UserOpenid, data.MsgTemplateId, data.IsAccepted)
	}, noticeNoticeSubscribeSettingIdKey, noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey)
	return ret, err
}
func (m *defaultNoticeSubscribeSettingModel) Update(ctx context.Context, newData *NoticeSubscribeSetting) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	noticeNoticeSubscribeSettingIdKey := fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, data.Id)
	noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey := fmt.Sprintf("%s%v:%v", cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix, data.UserOpenid, data.MsgTemplateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, noticeSubscribeSettingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserOpenid, newData.MsgTemplateId, newData.IsAccepted, newData.Id)
	}, noticeNoticeSubscribeSettingIdKey, noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey)
	return err
}

func (m *defaultNoticeSubscribeSettingModel) TransUpdate(ctx context.Context, session sqlx.Session, newData *NoticeSubscribeSetting) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	noticeNoticeSubscribeSettingIdKey := fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, data.Id)
	noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey := fmt.Sprintf("%s%v:%v", cacheNoticeNoticeSubscribeSettingUserOpenidMsgTemplateIdPrefix, data.UserOpenid, data.MsgTemplateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, noticeSubscribeSettingRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, newData.UserOpenid, newData.MsgTemplateId, newData.IsAccepted, newData.Id)
	}, noticeNoticeSubscribeSettingIdKey, noticeNoticeSubscribeSettingUserOpenidMsgTemplateIdKey)
	return err
}

func (m *defaultNoticeSubscribeSettingModel) List(ctx context.Context, page, limit int64) ([]*NoticeSubscribeSetting, error) {
	query := fmt.Sprintf("select %s from %s limit ?,?", noticeSubscribeSettingRows, m.table)
	var resp []*NoticeSubscribeSetting
	//err := m.conn.QueryRowsCtx(ctx, &resp, query, (page-1)*limit, limit)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, (page-1)*limit, limit)
	return resp, err
}

func (m *defaultNoticeSubscribeSettingModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultNoticeSubscribeSettingModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*NoticeSubscribeSetting, error) {

	builder = builder.Columns(noticeSubscribeSettingRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*NoticeSubscribeSetting
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*NoticeSubscribeSetting, error) {

	builder = builder.Columns(noticeSubscribeSettingRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*NoticeSubscribeSetting
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*NoticeSubscribeSetting, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(noticeSubscribeSettingRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*NoticeSubscribeSetting
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*NoticeSubscribeSetting, error) {

	builder = builder.Columns(noticeSubscribeSettingRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*NoticeSubscribeSetting
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*NoticeSubscribeSetting, error) {

	builder = builder.Columns(noticeSubscribeSettingRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*NoticeSubscribeSetting
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultNoticeSubscribeSettingModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultNoticeSubscribeSettingModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNoticeNoticeSubscribeSettingIdPrefix, primary)
}

func (m *defaultNoticeSubscribeSettingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeSubscribeSettingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNoticeSubscribeSettingModel) tableName() string {
	return m.table
}
