// Code generated by goctl. DO NOT EDIT.
// Source: notice.proto

package server

import (
	"context"

	"looklook/app/notice/cmd/rpc/internal/logic"
	"looklook/app/notice/cmd/rpc/internal/svc"
	"looklook/app/notice/cmd/rpc/pb"
)

type NoticeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNoticeServer
}

func NewNoticeServer(svcCtx *svc.ServiceContext) *NoticeServer {
	return &NoticeServer{
		svcCtx: svcCtx,
	}
}

func (s *NoticeServer) NoticeLotteryDraw(ctx context.Context, in *pb.NoticeLotteryDrawReq) (*pb.NoticeLotteryDrawResp, error) {
	l := logic.NewNoticeLotteryDrawLogic(ctx, s.svcCtx)
	return l.NoticeLotteryDraw(in)
}
