// Code generated by goctl. DO NOT EDIT.
package types

type VerifyEventReq struct {
	Signature string `form:"signature"`
	Timestamp string `form:"timestamp"`
	Nonce     string `form:"nonce"`
	Echostr   string `form:"echostr"`
}

type VerifyEventResp struct {
}
