// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	vote "looklook/app/vote/cmd/api/internal/handler/vote"
	"looklook/app/vote/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/vote/createVote",
				Handler: vote.CreateVoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vote/updateVote",
				Handler: vote.UpdateVoteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/vote/v1"),
	)
}
